export interface Khodam {
  name: string;
  rarity: string;
}

export const commonKhodams: Khodam[] = [
  { name: "Ubur-ubur Terbang", rarity: "common" },
  { name: "Singa Laut Melompat", rarity: "common" },
  { name: "Harimau Terbang", rarity: "common" },
  { name: "Katak Berlari", rarity: "common" },
  { name: "Kupu-kupu Raksasa", rarity: "common" },
  { name: "Elang Terbang Rendah", rarity: "common" },
  { name: "Cicak Gajah", rarity: "common" },
  { name: "Kura-kura Terbang", rarity: "common" },
  { name: "Ikan Berekor Panjang", rarity: "common" },
  { name: "Landak Berteriak", rarity: "common" },
  { name: "Kuda Laut Tertawa", rarity: "common" },
  { name: "Kucing Api", rarity: "common" },
  { name: "Gajah Terbang", rarity: "common" },
  { name: "Burung Hantu Berseri", rarity: "common" },
  { name: "Kepiting Terbang", rarity: "common" },
  { name: "Ular Melompat", rarity: "common" },
  { name: "Laba-laba Berekor", rarity: "common" },
  { name: "Kodok Berbulu", rarity: "common" },
  { name: "Kanguru Terbang", rarity: "common" },
  { name: "Katak Kuning Terbang", rarity: "common" },
  { name: "Banteng Berteriak", rarity: "common" },
  { name: "Marmut Terbang", rarity: "common" },
  { name: "Belalang Bergemuruh", rarity: "common" },
  { name: "Kura-kura Berekor", rarity: "common" },
  { name: "Landak Lompat", rarity: "common" },
  { name: "Kuda Nil Terbang", rarity: "common" },
  { name: "Burung Rajawali Melompat", rarity: "common" },
  { name: "Kucing Merak", rarity: "common" },
  { name: "Gorila Terbang", rarity: "common" },
  { name: "Kumbang Berlari", rarity: "common" },
  { name: "Paus Terbang", rarity: "common" },
  { name: "Ikan Paus Berteriak", rarity: "common" },
  { name: "Katak Terbang", rarity: "common" },
  { name: "Kelelawar Berlari", rarity: "common" },
  { name: "Panda Terbang", rarity: "common" },
  { name: "Burung Merpati Terbang", rarity: "common" },
  { name: "Kupu-kupu Tertawa", rarity: "common" },
  { name: "Gajah Berbulu", rarity: "common" },
  { name: "Belut Terbang", rarity: "common" },
  { name: "Landak Berlari", rarity: "common" },
  { name: "Jerapah Terbang", rarity: "common" },
  { name: "Cicak Merangkak", rarity: "common" },
  { name: "Kodok Tertawa", rarity: "common" },
  { name: "Kucing Terbang", rarity: "common" },
  { name: "Sapi Melompat", rarity: "common" },
  { name: "Babi Berteriak", rarity: "common" },
  { name: "Katak Gendut Terbang", rarity: "common" },
  { name: "Keledai Terbang", rarity: "common" },
  { name: "Ular Hutan Terbang", rarity: "common" },
];

export const rareKhodams: Khodam[] = [
  { name: "Sepuh Merendah", rarity: "rare" },
  { name: "Phoenix Abadi Seperti Cinta Kita", rarity: "rare" },
  { name: "Naga Bonar", rarity: "rare" },
  { name: "Kucing Garong Joget", rarity: "rare" },
  { name: "Griffin Bersirip", rarity: "rare" },
  { name: "Unicorn Kepala Lima", rarity: "rare" },
  { name: "Pegasus Sayap Ayam", rarity: "rare" },
  { name: "Feniks Api Menyala Abangku", rarity: "rare" },
  { name: "Ulat Pemakan Naga", rarity: "rare" },
  { name: "Kelpie Darat", rarity: "rare" },
];
